[build]
  functions = "netlify/functions"
  publish = "packages/app/dist"
  command = "common/scripts/install-run-rush.js install && rush install --no-link && rush link && rush rebuild"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200