[build]
  functions = "netlify/functions"
  publish = "packages/app/dist"
  command = "node common/scripts/install-run-rush.js install && rush build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200