[build]
  command = "(pnpm install --frozen-lockfile=false && pnpm build) || (npm install -g pnpm && pnpm install --frozen-lockfile=false && pnpm build)"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200