name: CI Setup
description: Setup Project
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      name: 'Setup PNPM'
      with:
        version: 7
    - uses: actions/setup-node@v3
      name: 'Setup Node'
      with:
        node-version: 16
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      shell: bash
