name: Shayne CI

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch
      - uses: ./.github/actions/setup-env
        name: Setup Environment
      - run: pnpm lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch
      - uses: ./.github/actions/setup-env
        name: Setup Environment
      - run: pnpm test
