name: Shayne CI

on: push

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch
      - uses: ./.github/actions/setup-env
        name: Setup Environment

      - run: pnpm lint
        shell: bash

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch
      - uses: ./.github/actions/setup-env
        name: Setup Environment

      - run: pnpm test
        shell: bash

  Integration-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Branch
      - uses: ./.github/actions/setup-env
        name: Setup Environment
      - run: pnpm -F shayne-portfolio-frontend exec playwright install --with-deps
        name: Install Playwright Browsers

      - run: pnpm -F shayne-portfolio-frontend playwright:ci
        shell: bash
