name: Shayne CI

on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-env
      - run: pnpm lint

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-env
      - run: pnpm test
